### ISSUE TITLE
The array passed as an argument is not updated when the method returns

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#10]
**Describe the bug**
Some classes in .NET have methods with arguments based on native types arrays. Using the method [Send](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.send?view=netcore-3.1#System_Net_Sockets_Socket_Send_System_Byte___) of the [Socket](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket) class everything goes fine.
When is used the method [Receive](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receive?view=netcore-3.1#System_Net_Sockets_Socket_Receive_System_Byte___System_Int32_System_Int32_System_Net_Sockets_SocketFlags_System_Net_Sockets_SocketError__) a developer expects, upon the methods returns, that the array as first argument is updated with the data received from the socket.

**To Reproduce**
1. Create a Java code which use the Socket class
2. Connects to an open socket endoint 
3. Call [Receive](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receive?view=netcore-3.1#System_Net_Sockets_Socket_Receive_System_Byte___System_Int32_System_Int32_System_Net_Sockets_SocketFlags_System_Net_Sockets_SocketError__) and wait coming data
4. When the method returns and return value is major than 0 (means data was received) the array used as buffer remains empty

**Expected behavior**
At point 4 of the steps to reproduce it is expected that the buffer was filled in with the data received frm the socket

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 10

**Additional context**
Tested on both .NET **Framework** and **Core**

**Comment by mariomastrodicasa** [comment]
The bug raised have a similar root cause to the issue #9, but here the problem is more related to the samantic of the methods involved and not to a possible type mapping. Both _Send_ and _Receive_ use a buffer of byte array, but each function use it in a different way:
- _Send_ does not update the buffer
- _Receive_ can update the buffer

[JCOBridge](https://www.jcobridge.com) has a special class to manage conditions where Java expect a variable can be updated from .NET: the Java code can use [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) to instruct the bridge on this.
As stated before the reflection does not give any information on the semantic so a workaround, when the developer encounter a condition like this, is to use the following snippet:

```Java
byte[] bytes = new byte[128];
Socket sender = new Socket(.......);
// all initial operations
JCRefOut<byte[]> jcr = JCRefOut.Create(bytes); // THIS CREATES THE OBJECT FOR JCOBRIDGE

JCObject jco = (JCObject) sender.getJCOInstance();
int bytesRec = (int) jco.Invoke("Receive", jcr, ....); // HERE IS MADE A DIRECT CALL USING JCOBRIDGE API

// all other operations

```

The previous snippet is an extraction of the code of the reflected method, but use the [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) container and not directly the array.
To solve the issue during the reflection it is possible to wraps always arrays with [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html), but in my opinion it is unuseful. Most of the methods have a behavior like the Send and they don't need to wrap the inputs.

**Comment by marcocappolimases** [comment]
Manually encapsulate the parameters inside a  [JCRefOut ](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html)is a good solution for experts, but, although well described in example and documentation, is not a transparent solutions and can be out of the range for most of the average users.

I explored the feasibility and consequence of a transparent solution,  evaluating quantity and kind of arrays parameters in the reflected classes.
The methods with array parameters are distributed as follows:

core 4.3%   2751/63696
framework 5.6% 4842/85222

looking inside the methods is clear that most of them doesn't need a [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html), but i cannot figure out how to automatically discriminate the different cases. Anyway with this numbers the overhead in terms of performance and size can represent a good price to pay for the gain in usability. 
A possible solution can be to add a reflection option for the user that enable/disable the wrapping of array, this way the user can opt for performance/size disabling the array wrapping, if not needed in the specific project.

This considerations are general, and is not to be excluded that a deepest analysis can individuate a way to automatically discriminate a series of condition where the array wrapping can be surely avoided, reducing impact in terms of performances and size.

**Comment by mariomastrodicasa** [comment]
@marcocappolimases your idea is feasable, but it is not clear the coverage you reported: had you evaluated methods with any kind of array or had you limited it to the supported array of [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html)?

The problem was raised from methods using arrays of native types and, as reported from the method [Create](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html#Create-T:A-), not every array type are managed from [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html).
To be inline with the idea behind the JCOreflector project, we must duplicate the methods with array because a developer shall face with the same signature available in .NET and have methods with [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) to overcome the issue.
In any case we must limit the methods duplication to the methods with arrays of native Java types, surely avoiding counting of extra methods for statistics (see issue #3).

**Comment by marcocappolimases** [comment]
Methods with **any kind** of array are evaluated In the reported coverage. 
Considering only  supported types by [JCRefOut ](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) will drastically reduce the number of methods to be duplicated.

**Comment by marcocappolimases** [comment]
This issue can be closed. 
I tested methods with duplicated signature (method duplicated when signature contains array of native types) introduced with commit [79d4346  ](https://github.com/masesgroup/JCOReflector/commit/79d43461cc9dffeae5d873a9dae5db416fd636de) and used one of them in [netreflected-tests/src/hierarchy/HelloHierarchy.java](https://github.com/masesgroup/JCOReflector/blob/master/netreflected-tests/src/hierarchy/HelloHierarchy.java) example.

As followup action i suggest to modify the socket examples that implement the workaround suggested in this [comment](https://github.com/masesgroup/JCOReflector/issues/10#issuecomment-652572559).

**Comment by mariomastrodicasa** [comment]
@marcocappolimases the issue shall be opened again because #25 is usable only in runtime: during compilation it is mandatory to have JCOBridge.jar to resolve [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) type directly used in some reflected methods. 
To solve the issue the reflector shall inject a new type (JCORefOut can be the name) which wraps or manage the real [JCRefOut](https://www.jcobridge.com/api-java/org/mases/jcobridge/JCRefOut.html) recognized from the underlying JCOBridge.
