### ISSUE TITLE
Accept multiple root assembly in reflector engine instead a single one for each execution.

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#17]
**Is your feature request related to a problem? Please describe.**
Sometimes it is needed (especially in .NET Framework) to repeat the reflection operation against multiple assemblies. With a list of input assemblies the operation can be done without further manual intervention.

**Describe the solution you'd like**
Multiple assemblies could be written in the "Assembly name" TextBox and these assemblies can be sent to the reflector engine.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
I added the requested feature to the reflector engine. Until now the engine can be used only from Windows platform because it is coupled to WPF. Maybe can be interesting to add a CLI tool to invoke the reflection from the command-line and use it in other supported platform (i.e. Linux). @marcocappolimases what do you think?
