### ISSUE TITLE
Add a CLI tool to invoke the reflection on other supported platforms

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#18]
**Is your feature request related to a problem? Please describe.**
The reflection engine can  only be used on Windows platform. 

**Describe the solution you'd like**
Add a command line interface tool for other supported platforms (e.g. linux)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
I started the modification creating two different tools: a GUI and a CLI, both shares the same engine which was moved on a different project. At this stage the CLI tool is only a starting project because it is not clear for me which is the best strategy to use for its development. I'm explaining better my position. There are multiple inputs to be managed and all of them shall be translated into a `ReflectorEventArgs`, if the CLI tool accept in input a single file with the required information we don't need to manipulate too much the command-line of the CLI. Converting `ReflectorEventArgs` into a serializable object it is possible to write its content in a file, the user can manipulate the content and loads it to instruct the CLI tool. In future stages it is possible to add other features to the CLI. @marcocappolimases do you have other ideas?

**Comment by marcocappolimases** [comment]
I think that the use of a configuration file is the best chose in case of CLI tools that require/accept multiple options and parameters, such configuration file facilitate the task of use different configurations, and can also be used in the actual Graphical configuration tool to save and manage the configurations used in the build process. 
Working this way it will become also easy, in the future, to implement a cross platform user interface for the CLI tool that shall rely only on the configuration file.

**Comment by mariomastrodicasa** [comment]
> I think that the use of a configuration file is the best chose in case of CLI tools that require/accept multiple options and parameters, such configuration file facilitate the task of use different configurations, and can also be used in the actual Graphical configuration tool to save and manage the configurations used in the build process.

I will add the ability of the GUI interface to save the serialized command for its reuse and eventually reload it. Meantime the classes used to send options to the engine will be made serializable so it is possible to save and load it.

> Working this way it will become also easy, in the future, to implement a cross platform user interface for the CLI tool that shall rely only on the configuration file.

Some of the configuration files can be stored on repository and becomes templates.

**Comment by marcocappolimases** [comment]
CLI doesn't return an error code, in case of error, when used in command line. And it doesn't recognize JDK tools when used in a Linux machine.

**Comment by marcocappolimases** [comment]
It is possible to add a command line switch to override the JDK path? 
This can be useful for the management of continuous integration workflows #21 .

**Comment by mariomastrodicasa** [comment]
> It is possible to add a command line switch to override the JDK path?
> This can be useful for the management of continuous integration workflows #21 .

I added a command line switch named _jdk_ which accept the path to the JDK folder.
