### ISSUE TITLE
no Read method in Stream.java (net461) 

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#20]
**Describe the bug**
The Stream reflected class have no Read method implemented.

**To Reproduce**
N/A

**Expected behavior**
As stated in [msdn documentation](https://docs.microsoft.com/it-it/dotnet/api/system.io.stream?view=netcore-3.1) the Read method shall be available on the class.

**Screenshots**
Here you can see a diff between the netcore3.1 reflected class and the net461 class
![image](https://user-images.githubusercontent.com/48452565/93758747-458d1300-fc09-11ea-8e5e-1ef94ebcee1f.png)

**Desktop (please complete the following information):**
 N/A

**Additional context**
Further analysis are needed to understand if other class are affected by this bug.

**Comment by mariomastrodicasa** [comment]
@marcocappolimases I checked what happens during reflection analysis and the problem comes from the method definition: the first parameter reports to be an Out param while the [online documentation](https://docs.microsoft.com/it-it/dotnet/api/system.io.stream.read?view=netframework-4.8#System_IO_Stream_Read_System_Byte___System_Int32_System_Int32_) reports another signature. We don't manage Out parameter until now (see #9). Here below a screenshot:

![image](https://user-images.githubusercontent.com/48451703/93769655-678f9100-fc1b-11ea-9a29-04e81f7ca202.png)

**Comment by mariomastrodicasa** [comment]
I'm closing the issue waiting to implement #9.
