### ISSUE TITLE
Methods order inside generated files changes

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#5]
**Describe the bug**
When you do an **Execute Build** most of the generated reflected class files are signaled as modified by Git.
What changes is the order of Methods Implementation, not the code of the Methods inside the java class. 
This is not good, because nothing changed except Methods implementation order. This behavior should be avoided to let git individuate only the files that have real modifications inside. 

**To Reproduce**
_the following steps are for netcore, but the bug can be reproduce with similar steps for framework_
1. Open the **JCOReflector Builder**
2. Put the following string in the **Assembly name**  field: "PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" .
3. Press **Execute Build**.
4. Check with Git the modified files in netreflected\src\Core\

**Expected behavior**
It is expected, starting from the same .Net Assembly, that the methods in the methods section have the same order in every automatic reflected code generation.

**Screenshots**
This is an example of Methods with changed order.
![image](https://user-images.githubusercontent.com/48452565/85580341-ef292c00-b63b-11ea-9d7c-634905028694.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.18362

**Additional context**
The bug was find in a Windows with IT localization.

**Comment by mariomastrodicasa** [comment]
The methods are parsed sequencially on the MethodInfo[] array returned from the GetMethods call. As reported in the remarks section of [GetMethods](https://docs.microsoft.com/en-us/dotnet/api/system.type.getmethods?view=netcore-3.1#System_Type_GetMethods) the order is not guaranteed:

_The GetMethods method does not return methods in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which methods are returned, because that order varies._

The same is valid for [GetConstructors](https://docs.microsoft.com/en-us/dotnet/api/system.type.getconstructors?view=netcore-3.1#System_Type_GetConstructors), [GetEvents](https://docs.microsoft.com/en-us/dotnet/api/system.type.getevents?view=netcore-3.1#System_Type_GetEvents_System_Reflection_BindingFlags_), [GetProperties](https://docs.microsoft.com/en-us/dotnet/api/system.type.getproperties?view=netcore-3.1#System_Type_GetProperties_System_Reflection_BindingFlags_)

@marcocappolimases, I propose to reorder the methods, events and properties using something like a sorted dictionary based on the hash of the string representing the method and then iterates on the sorted result.

**Comment by marcocappolimases** [comment]
Double checked: is ok. 
The bug is closed.
