### ISSUE TITLE
Missing java class hierarchy 

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/JCOReflector#6]
**Is your feature request related to a problem? Please describe.**
The inheritance of the classes and interfaces is missing. It can be useful to have this feature to better reuse .NET code within Java.

**Describe the solution you'd like**
The generated classes and interfaces should have the right hierarchy miming the one available in the reflected .NET Framework/Core.
E.G.: The .NET System.IO.FileStream derives from System.IO.Stream, also the FileStream java Class inside the package system.io should extend system.io.Stream, by now both classes extends NetObject.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
@marcocappolimases the missing inheritance is strictly related to another missing feature: generic types. Some types have in its hierarchy generic types and without them is not possible to have a complete hierarchy.
The actual project can create a reduced inheritance: the example you made can be implementable.

Please @marcocappolimases: open a feature request related to generic types.

**Comment by mariomastrodicasa** [comment]
During the preliminary tests related to #7 I seen the generated documentation is too big. Too many classes with inheritance repeat the methods and this is reflected into documentation too: an example is [DataGrid](https://docs.microsoft.com/it-it/dotnet/api/system.windows.controls.datagrid) where all methods of the class chain are repeated. Moreover all classes derived from [FrameworkElement ](https://docs.microsoft.com/it-it/dotnet/api/system.windows.frameworkelement), [UIElement](https://docs.microsoft.com/it-it/dotnet/api/system.windows.uielement), and so on reimplement everything.

I propose to start a first implementation of class hierarchy excluding generics types:

- Found the parent [Type](https://docs.microsoft.com/it-it/dotnet/api/system.type) of the [Type](https://docs.microsoft.com/it-it/dotnet/api/system.type) under analysis
- If the parent [Type](https://docs.microsoft.com/it-it/dotnet/api/system.type) can be implemented set it as the parent of the type under analysis otherwise use the actual logic and parent [Type](https://docs.microsoft.com/it-it/dotnet/api/system.type) (NetObject, NetException)
- Avoid implementation of any method of the base class: virtual methods overridden in the derived class can use the method of the parent class because the target object will be the same 
- The same is valid for the interfaces: if the [Type](https://docs.microsoft.com/it-it/dotnet/api/system.type) under analysis implements some interfaces we can add them into the Java _implements_ keyword.

**Comment by mariomastrodicasa** [comment]
Since the Java classes are accessor to the CLR counterpart I think we can change the prototype of Java functions adding the **_final_** keyword on the methods the reflector produces, not the class. The override of the methods is a _non-sense_ because the real logic is within .NET. @marcocappolimases have you found some conditions or use-cases that contradict my opinion?

**Comment by marcocappolimases** [comment]
My opinion is that to have all methods defined as **final** is good, because, as stated, the logic is on the .NET side. 
The only possible reason for an override can be a workaround, but also in this case the source code is available and the right thing to do is open a bug and (ideally) submit a PR.

**Comment by mariomastrodicasa** [comment]
During some tests on class hierarchy I discovered a problem: some methods, events and properties use the **new** operator in derived classes. Using the **_final_** keyword avoid a right compilation of the reflected classes. Meantime I discovered other issues with inheritance:
- [TextDecorationCollectionConverter.ConvertFromString](https://docs.microsoft.com/en-us/dotnet/api/system.windows.textdecorationcollectionconverter.convertfromstring) is defined static, but parent class [TypeConverter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter) defines an instance method with the same signature [TypeConverter.ConvertFromString](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.convertfromstring?view=netframework-4.8#System_ComponentModel_TypeConverter_ConvertFromString_System_String_). 
- .NET C# has the [new modifier](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/new-modifier) feature, some classes use this feature to change the signature of the methods, especially in the return type:
  - [CommaDelimitedStringCollection.Add](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.commadelimitedstringcollection.add) does not return anything (it is **void**), while [StringCollection.Add](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.stringcollection.add) returns an **int**
  - [HttpRequestCachePolicy.Level](https://docs.microsoft.com/en-us/dotnet/api/system.net.cache.httprequestcachepolicy.level) returns [HttpRequestCacheLevel](https://docs.microsoft.com/en-us/dotnet/api/system.net.cache.httprequestcachelevel), but [RequestCachePolicy.Level](https://docs.microsoft.com/en-us/dotnet/api/system.net.cache.requestcachepolicy.level) returns [RequestCacheLevel](https://docs.microsoft.com/en-us/dotnet/api/system.net.cache.requestcachelevel)

in all cases there is the [new modifier](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/new-modifier) applied: see [HttpRequestCachePolicy](https://referencesource.microsoft.com/System/R/13240b9dc1b551b7.html) source code.

We need to identify a way to check if a method, event or property has the [new modifier](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/new-modifier). If we are able to identify the [new modifier](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/new-modifier) during reflection, my idea is to add **New** to the end of the reflected name. Find the [new modifier](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/new-modifier) is tricky, maybe it is possible, for every method, event or property, to check the class hierarchy searching for similar signature (see https://stackoverflow.com/questions/6634303/how-do-i-detect-the-new-modifer-on-a-field-using-reflection), but to reduce the impact on speed, another possibility is to list the classes affected by this behavior and eventually discard them from reflection.

**Comment by marcocappolimases** [comment]
To Add a New suffix to the end of the reflected name seams a good solution, but can be not enough in case of more then a **new** inside an inheritance hierarchy.
My suggestion is to insert also the name of the class to the reflected name to have an unique signature in the java world.

**Comment by marcocappolimases** [comment]
A test file for the feature was added in commit [87d6629](https://github.com/masesgroup/JCOReflector/commit/87d6629bbdf71a11d6a9907d6ed4c1b842578753) the issue can be closed.

**Comment by mariomastrodicasa** [comment]
@marcocappolimases looking inside your example I see that [Dispose](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) method is called within the _finally_ of a _try...finally_ block. https://stackoverflow.com/questions/2016299/does-java-have-a-using-statement reports how Java intoduced [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) interface to manage a behavior similar to the [using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement). I will open a feature request to mimic [using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) with [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html).

**Comment by marcocappolimases** [comment]
Interfaces Hierarchy still be missed for classes implementations.

**Comment by mariomastrodicasa** [comment]
> Interfaces Hierarchy still be missed for classes implementations.

@marcocappolimases you are right. Anyway many .NET classes implements the interface methods as [explicit ](https://docs.microsoft.com/it-it/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) and these methods are not available during reflection because they are not public (we avoid to reflect non-Public mehods). Java does not have explicit interface or something similar: if the class declares to `implements` an interface it must be implemented at all.
In this case we are facing a problem: Java needs methods not available in .NET.
We must find a solution for hierarchy, until now it is possible to use the `To<interfaceName>` method available on every interface.

**Comment by mariomastrodicasa** [comment]
I thinked about a possible solution. As written in https://github.com/masesgroup/JCOReflector/issues/6#issuecomment-686596662, Java expects the methods are implemented, but .NET does not expose them if there isn't an explict cast to the interface. My idea is to use the `@Deprecated` annotation of Java to inform the user that the method cannot be used without an explicit cast. In https://docs.oracle.com/javase/8/docs/technotes/guides/javadoc/deprecation/deprecation.html the latest example is very clear about this point. The idea is to create a template which gives to the user enough information, a possible snippet is the following one:

```java
/**
 * @deprecated  Not for public use because the method is implemented with an explicit interface.
 *    Use the static ToINTERFACE_NAME method available in INTERFACE_NAME to obtain an object with an invocable method
 */
@Deprecated public RETURN_TYPE METHOD_NAME(METHOD_PARAMS) {
   throw new UnsupportedOperationException("Not for public use because the method is implemented with an explicit interface.");
}
```
